### ISSUE TITLE
R.REPLACE IS NOT A FUNCTION ISSUE

### ISSUE THREAD

**Issue by eiazeez** [filiphric/cypress-plugin-api#133]
Sometimes, and i don't know why or what cause this, i get this error when i use cy.api. 
![image](https://github.com/filiphric/cypress-plugin-api/assets/92765887/424cb5d0-06d4-4924-8d77-3467a4a8afe2)

To resolve this issue, i put .toString() between "r"and "replace" function, in >> node_modules/cypress-plugin-api/dist/support.js line 9 <<
Here a example:

![image](https://github.com/filiphric/cypress-plugin-api/assets/92765887/90f19fc7-d655-4df7-a47e-17131234c5af)

**Comment by filiphric** [comment]
hey @eiazeez! I’m back to working on this. would it be possible for you to provide an example response that causes this issue? there’s probably something wrong with how data is parsed and I’m assuming that it has something to do with the response body, or headers

**Comment by eiazeez** [comment]
Hey, @filiphric 
As i shared, i don't know how exactly to reproduce. Sometimes i get this error, sometimes not. I tried to reproduce a step by step scenario but it's intermitent behave

**Comment by Dale-777** [comment]
I am seeing this issue when the response body is HTML


**Content-Type | text/html; charset=utf-8**


```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Cannot POST /datahub/v1/csv/upload</pre>
    </body>
</html>
```

```
index-DzmIZ6wu.js:96640 TypeError: r.replace is not a function
    at o (webpack://@doitint/client-api-tests/../../../node_modules/cypress-plugin-api/dist/support.js:9:212)
    at Array.map (<anonymous>)
    at Object.o [as encode] (webpack://@doitint/client-api-tests/../../../node_modules/cypress-plugin-api/dist/support.js:9:212)
    at Object.highlight (webpack://@doitint/client-api-tests/../../../node_modules/cypress-plugin-api/dist/support.js:9:3805)
    at P (webpack://@doitint/client-api-tests/../../../node_modules/cypress-plugin-api/dist/support.js:10:1036)
    at Fe (webpack://@doitint/client-api-tests/../../../node_modules/cypress-plugin-api/dist/support.js:12:1536)
    at Context.eval (webpack://@doitint/client-api-tests/../../../node_modules/cypress-plugin-api/dist/support.js:14:2091)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (http://localhost:57764/__cypress/runner/cypress_runner.js:3486:19)
    at Promise._then (http://localhost:57764/__cypress/runner/cypress_runner.js:1239:17)
    at Promise.then (http://localhost:57764/__cypress/runner/cypress_runner.js:1132:17)
    at next (http://localhost:57764/__cypress/runner/cypress_runner.js:144025:64)
    at <unknown> (http://localhost:57764/__cypress/runner/cypress_runner.js:144046:16)
    at tryCatcher (http://localhost:57764/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:57764/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:57764/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:57764/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:57764/__cypress/runner/cypress_runner.js:1701:18)
    at <unknown> (http://localhost:57764/__cypress/runner/cypress_runner.js:2392:25)
```

![Screenshot 2024-12-10 at 14 12 12](https://github.com/user-attachments/assets/1ae65738-0e34-4abf-b7ce-579b65c3850b)

**Comment by kevinmora47** [comment]
Hi guys, I just make a workaround to solve this issue, it not the best way to implement the fix, but it works!
Basically, you'll need to overwrite the command with a wrapper, here's the code snippet:
```
/// <reference types="../types/global.d.ts" />

/**
 * Custom wrapper for cy.api to handle the r.replace error in cypress-plugin-api
 * This fixes the issue where the plugin tries to call .replace() on non-string values
 */

// Store the original cy.api command before we override it
let originalApiCommand: any;

// Override the cy.api command with our wrapper
Cypress.Commands.overwrite('api', (originalFn, options) => {
  // Ensure body is properly handled to avoid the r.replace error
  if (options && options.body !== undefined) {
    // Convert body to string if it's an object to prevent the plugin error
    // The plugin expects string values in certain contexts
    if (typeof options.body === 'object' && options.body !== null) {
      // Keep the original object but ensure it can be safely processed
      options.body = JSON.parse(JSON.stringify(options.body));
    }
  }
  
  // Call the original cy.api command with the processed options
  return originalFn(options);
}); 
```
